POST http://localhost:18079/articles/
Content-Type: application/json

{
    "name": "GDV-DL",
    "price": 199.90
}

###

GET http://localhost:8079/articles/

###

PATCH http://localhost:8079/articles/fc0b7122-c068-46b5-978b-137abab7fd8f
Content-Type: application/json

{
    "uuid": "fc0b7122-c068-46b5-978b-137abab7fd87"    
}